utils::globalVariables(
  names = c(
    "install.packages",
    "%chin%",
    ".N",
    "filepath",
    "dbConnect",
    "odbc",
    "GET_SQL_QUERY",
    "dbSendQuery",
    "dbFetch",
    "sql.string",
    "SQL_QUERY_FILEPATH",
    "SQL_FILEPATH",
    "library",
    ":=",
    "is.data.table",
    ".SD",
    ".I",
    ".",
    "uniqueN",
    "missing_dates",
    "unique_dates",
    "dates_between",
    "rbindlist",
    "date_day",
    "date_dayofweekname",
    "date_month",
    "date_quarter",
    "date_year",
    "date_ymd",
    "date_ymd_month",
    "date_ymd_week",
    "fifelse",
    "frollmean",
    "is_christmas_around",
    "is_christmas_day",
    "is_covid_shock",
    "is_newyear_around",
    "is_newyear_day",
    "is_other_holiday_day",
    "is_weekend",
    "set",
    "shift",
    "ID",
    "lm",
    "mod_formula",
    "FULL_FORMULA",
    "RSQUARED",
    "ADJ_RSQUARED",
    "MSE",
    "RMSE",
    "fitted",
    "QUERY_PATH"
        
  )
)



  